# Stage that builds the application, a prerequisite for the running stage
FROM maven:3-openjdk-17-slim as build
RUN curl -sL https://deb.nodesource.com/setup_16.x | bash -
RUN apt-get update -qq && apt-get install -qq --no-install-recommends nodejs

# Stop running as root at this point
RUN useradd -m myuser
WORKDIR /usr/src/app/
RUN chown myuser:myuser /usr/src/app/
USER myuser

# Copy pom.xml and prefetch dependencies so a repeated build can continue from the next step with existing dependencies
COPY --chown=myuser pom.xml ./
RUN mvn dependency:go-offline -Pproduction

# Copy all needed project files to a folder
COPY --chown=myuser:myuser src src
COPY --chown=myuser:myuser frontend frontend
COPY --chown=myuser:myuser package.json ./

# Using * after the files that are autogenerated so that so build won't fail if they are not yet created
COPY --chown=myuser:myuser package-lock.json* pnpm-lock.yaml* webpack.config.js* ./

# Build the production package, assuming that we validated the version before so no need for running tests again
RUN mvn clean package -DskipTests -Pproduction

# NextJs Running stage: the part that is used for running the application
FROM node:16.16.0

RUN apt-get update \
 && apt-get install default-jre -y \
 && apt-get install default-jdk -y

RUN mkdir -p /usr/src/app

WORKDIR /usr/src/app

## copy built vaadin application to running stage
COPY --from=build /usr/src/app/target/*.jar /usr/src/app/app.jar
COPY package*.json ./

RUN npm install
RUN npm install --global nodemon

COPY . .

EXPOSE 3000 8080

CMD ["npm", "run", "dev"]